version: "3"

services:
  app:
    build:
      context: ..
      args:
        - ENVIRONMENT=local
    ports:
      - "8080:8080"
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - .:/usr/src/app

  app-test:
    build:
      context: ..
      args:
        - ENVIRONMENT=test
    volumes:
      - .:/usr/src/app
    entrypoint: ["pytest", "tests"]
